### ISSUE TITLE
Support building images for different platform

### ISSUE THREAD

**Issue by LucaLanziani** [nearform/initium-cli#150]
At the moment when we run `initium build` the resulting image is based on the architecture of the machine we run the command on.

Initium is based on the assumption that running the command on CI or in your local environment should produce the same output, this is not the case for the image build.

**Comment by mablanco** [comment]
It seems that the best option is to rewrite the `Build()` function in the Docker service using https://pkg.go.dev/github.com/docker/buildx@v0.12.0. However, documentation only describes functions and constants and there are no examples or workflow description, so it's not clear how to use this module.

**Comment by mablanco** [comment]
After some discussion over the topic in today's standup it has been decided to change the scope of this task to enforce the building of `linux/amd64` images.

**Comment by mablanco** [comment]
```
$ docker inspect ghcr.io/mablanco/initium-nodejs-demo-app:initium-test | grep -E 'Architecture|Os'
        "Architecture": "amd64",
        "Os": "linux",
```
