### ISSUE TITLE
Build and deploy on PR

### ISSUE THREAD

**Issue by LucaLanziani** [nearform/initium-cli#26]
As a user I would like the application to build and deploy every time a new commit is pushed to a non-draft PR.

- the built artifact should be tagged with the branch name (format might be different if tags don't accept all characters of branches)
- the knative service fqdm should contain the branch name as well, possibly that could be the namespace we use when deploying the service. (app-name.branch-name)
- when the PR is merged the knative services (app-name.branch-name) should be removed, and the namespace should be deleted if that was the last service in the namespace.

### Desired outcome

Write a pipeline that implements the above
Embed the pipeline in the generated binary
Persist the pipeline as part of the init command

**Comment by vinicius-marinho-nearform** [comment]
Considering that this is a pipeline that will be used in a different environment, what should be the process of deploying? Should we use kind? Or let the client deploy and test in their own environment (maybe they have a development environment that could be used to test it, specially if they use and manage runners inside their environment)?
