### ISSUE TITLE
Check for update on very run of the CLI

### ISSUE THREAD

**Issue by LucaLanziani** [nearform/initium-cli#78]
CLI should check for updates and output a warning if a new version is available.

This step should be quick and never break the CLI

**You need to also update the CLI so it knows the version it is running at**

eg. if there is no internet connection this step should not fail but ignore and move on

**Comment by proxhavasi** [comment]
Interestingly Hashicorp built a custom endpoint for their products https://github.com/hashicorp/go-checkpoint/blob/master/versions.go

**Comment by proxhavasi** [comment]
The question in our case whether we want to grab the latest tag with Github API requests or should we build a release flow for a package manager first and use that?

**Comment by proxhavasi** [comment]
Maybe it's time to add a `--version` parameter to the CLI as well
